### ISSUE TITLE
Use PythonCall/JuliaCall instead of PyCall/pyjulia?

### ISSUE THREAD

**Issue by dingraha** [byuflowlab/OpenMDAO.jl#10]
I've been working on replacing OpenMDAO.jl's dependency on PyCall/pyjulia with [PythonCall and JuliaCall](https://github.com/cjdoris/PythonCall.jl). The benefits of PythonCall/Juliacall over the older PyCall/pyjulia libraries:

  * PythonCall and JuliaCall manage dependencies much better, using [CondaPkg](https://github.com/cjdoris/CondaPkg.jl) for Python dependencies in a Julia package, and [JuliaPkg](https://github.com/cjdoris/PyJuliaPkg) for Julia dependencies in a Python package
  * JuliaCall is able to pass a Julia `struct` without a copy, which gets around an annoying hack that OpenMDAO.jl uses now

The version of OpenMDAO.jl using PythonCall/JuliaCall is in the `pythoncall_juliacall` branch of my fork: https://github.com/dingraha/OpenMDAO.jl/tree/pythoncall_juliacall I've managed to get CI set up, and have some docs, too.

The switch wouldn't be too painful—the API is basically the same, though I did split the Julia-related code into two packages:

  * OpenMDAOCore.jl: A Julia-only package that defines the interface used to create OpenMDAO components from Julia code (`AbstractExplicitComp`, `AbstractImplicitComp`, etc.)
  * OpenMDAO.jl, a small wrapper package that has OpenMDAO itself (the actual Python package) as a dependency, along with OpenMDAOCore.jl. (The idea is a Julia user can install OpenMDAO.jl to get access to both OpenMDAOCore.jl and OpenMDAO itself, then use it from Julia.)

Current OpenMDAO.jl code would have to replace references to, say, `OpenMDAO.AbstractImplicitComp` or `OpenMDAO.setup!` with `OpenMDAOCore.AbstractImplicitComp` and `OpenMDAOCore.setup!`.

I was about to submit a pull request, but wanted to create this issue to give any current users a chance to weigh in. I don't imagine there are many out there. :-) @andrewning Does anyone from your research group use this currently? There are a handful of users here at Glenn (maybe three, counting me).

**Comment by andrewning** [comment]
Updating to PythonCall/JuliaCall is a good idea.
I don't have anyone using it at the moment.  We've been using a new package we've been putting together: https://github.com/byuflowlab/ImplicitAD.jl and I have some ideas to tie it into openmdao down the road.

**Comment by dingraha** [comment]
OK, I just merged the stuff with PythonCall/JuliaCall: https://github.com/byuflowlab/OpenMDAO.jl/pull/11 The CI and docs seem to be working. I'll leave this issue up for a bit for any users to react, then close.
